### ISSUE TITLE
Allow user to specify name and description for AVI Cloud registration

### ISSUE THREAD

**Issue by jpeters-vmw** [vmware/terraform-aws-avi-alb-deployment-aws#12]
### Is your feature request related to a problem? Please describe.

The current codebase sets the name and description that is used during AVI Cloud registration.  Users with multiple deployments of NSX ALB need different names when registering and typically have a naming convention they use.
Users of the module should be able to specify their own name and description used with AVI Cloud registration.

### Describe the solution you'd like

The user can add "name" and "description" parameters to the register_controller variable.  The avi-cloud-services-registration will use these values when registering the deployment with AVI Cloud.

**Comment by slarimore02** [comment]
Added the optional name and description parameters to the register_controller variable in [v1.0.11](https://github.com/vmware/terraform-aws-avi-alb-deployment-aws/releases/tag/v1.0.11)
