### ISSUE TITLE
Method PATCH not allowed error when updating cloud configuration with DNS profile on cluster deployments

### ISSUE THREAD

**Issue by jpeters-vmw** [vmware/terraform-aws-avi-alb-deployment-aws#19]
### Describe the bug

When deploying a cluster the Ansible task that updates cloud configuration with DNS profile fails with following error.

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error 405 Msg {\"detail\": \"Method 'PATCH' not allowed.\"} req: {'add': {'dns_provider_ref': 'https://<ip address>/api/ipamdnsproviderprofile/ipamdnsproviderprofile-1e9a5350-3684-425c-ac3c-ae5011e722d2#AWS_R53_DNS'}} api_context:None "}

### Reproduction steps

1. controller_ha = true
2. configure_dns_profile = {enabled=true, type=AWS}

### Expected behavior

The DNS Profile should be selected in the AWS Cloud configuration after deployment.

**Comment by jpeters-vmw** [comment]
@slarimore02 , looks like this was fixed already in your latest updates by changing to the use of the avi_cloud module.  However that change did not make it into the v1.0.2 release.  

Also lines 303 and 330 have the wrong vtype.  vtype: CLOUD_AZURE
Should be vtype: AWS.

**Comment by slarimore02** [comment]
v1.0.3 released and cloud type fixed.
